### ISSUE TITLE
Reg Edge browser parsing

### ISSUE THREAD

**Issue by omkumar87** [ua-parser/uap-java#22]
Hi

I have used this ua parser for parsing user agents.
It is returning chrome for the Edge browser.
Can you please add support for the same.

Thanks.

**Comment by mormegil-cz** [comment]
This repository does not contain the user-agent parsing data itself which is responsible for the mapping, it contains only the parsing support for Java. The problems in the data should be reported in the [`ua-core`](https://github.com/ua-parser/uap-core/issues) repository. And this bug was already [reported and fixed](https://github.com/ua-parser/uap-core/issues/233) (since 7 Jun).

**Comment by jeronimonunes** [comment]
How could I update the ua-core dependency of uap-java, so it would correctly parse the user-agent of Microsoft Edge? Or maybe the fix on the previous comment was to the old Microsoft Edge and the new Edgium now have the same bug!?!? Shouldn't a new release of this library be submitted to maven central?

The ua string that I'm trying to parse is: ```Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.56```

**Comment by bpossolo** [comment]
Hi @omkumar87 and @jeronimonunes 
Edge support was added in [release 1.4.4](https://github.com/ua-parser/uap-java/wiki/ChangeLog)

@jeronimonunes the user agent string you supplied now returns `Edge` for `userAgent.family`

Note: to get the latest version you'll want to upgrade to 1.5.0
